#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

if [ `uname` != "Linux" ]; then
  echo "› brew bundle"
  brew bundle
fi
# Run Homebrew through the Brewfile

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do 
  echo "Running ${installer}"
  sh -c "${installer}"
done
